### ISSUE TITLE
Unable to set Auth-Method to Primary in cli

### ISSUE THREAD

**Issue by djdta** [hashicorp/boundary#1320]
**Describe the bug**
Currently, when using the cli there is no ability to set the auth-method to the following to primary.

**To Reproduce**
1. Start a boundary controller
2. login to the boundary via token.
3. From the cli please create an auth-method with primary as an arg.

**Expected behavior**

To have the ability to set the auth-method to primary.

**Additional context**

**Comment by randallmorey** [comment]
Hi there!  Thanks for your interest in Boundary.  Each scope may have up to one primary auth method.  It is the scope where primary auth method is specified (rather than directly on auth methods).  To make an auth method primary it must first exist, then set `primary_auth_method_id` on the associated scope resource.  While auth method resources have an `is_primary` field, this is a read-only convenience.

**Comment by randallmorey** [comment]
[Here's an example of specifying a primary auth method for a scope using the CLI](https://learn.hashicorp.com/tutorials/boundary/oidc-auth#set-oidc-as-primary-login).
