### ISSUE TITLE
Permissions Model is Untenable

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/boundary#1791]
**Describe the bug**
The existing permissions model is untenable.  It is so complicated that I would imagine folks will avoid least privilege just to ensure functionality.  I don't have any confidence that the permissions I set are 1) correct or 2) least privilege.

**To Reproduce**
1. Start boundary in dev mode
2. Create a role at global scope and set grant scope to generated project scope
3. Add unprivileged `user` as principal
4. Add grant string `id=ttcp_1234567890;actions=read,authorize-session`
5. Login as user
6. See no targets in web UI or boundary app

**Expected behavior**
If I have a role that says `user` should be able to `read` and `authorize-session` on target `ttcp_1234567890` on the project scope, then I expect to see the target listed, else how would it be possible for user to do those things?

**Additional context**
Any permissions that are required in order for other permissions to take effect need to be adequately documented, but preferably avoided altogether.  I love the idea of this product but I have been unable to dial-in permissions since I launched our infrastructure six months ago.  It has been a big problem for us.

**Comment by jimlambrt** [comment]
I'm sorry you've had issues with setting up boundary permission.

I think, you're very close to a working example, but It would appear that you haven't granted "list" permission to the new user via ($ROLE == your newly created role):
`boundary roles add-grants -id $ROLE -grant="type=target;actions=list"`
This additional grant will give the new role the ability to only list the targets it's been granted some other privileges to (like authorize-session).   I might also suggest that you remove the `read` grant from the role, since it's not necessary to make a connection if that's all you wish to allow.

I hope this helps.

**Comment by micchickenburger** [comment]
Thanks for your quick response.  You're right that my example is missing that grant.  Under what conditions would I want a user to read and authorize a session for a target without them being able to list the targets for which they have access?  That's why this permissions model is too complicated.  I think that there is no need for a list grant at all.  Just list resources users have access to because they have access to them.

**Comment by jefferai** [comment]
Hi there! I think some of the confusion here is around what actions are being used against what resources/collections.

Generally speaking, Boundary is a collection-and-resource based API. As such, you can be granted permission against collections themselves (`create` and `list` mainly, and taking place against e.g. `/targets`) or specific resources (most other actions, taking place against e.g. `/targets/ttcp_1234567890`). So when you are trying to list targets, even though you have `read` permission on that resource, you're actually making a query against the collection itself, and lacking appropriate permissions on it.

If you _do_ have `list` permission on a collection, we ensure that we don't return items for which you don't have any permissions, so you would see that target because you have `read` and `authorize-session` but not targets for which you are unable to take any action.

The end result of this is that if you were to simply authorize a session or read the target by its ID via the CLI, it would work fine. However, the graphical UIs want to show you a list, and you don't have list permission on the target collection, so you're seeing nothing.

I think a tasker for us based on this is to add listing targets to the default set of grants we use when we create a default role when a new scope is created. That way it will "just work" in dev environments. This definitely is more friction for a common use case than we'd like, and you'd still only see targets for which you have available actions.

**Comment by jefferai** [comment]
By the by, if you haven't seen the resource table on the permissions page, it may prove useful: https://www.boundaryproject.io/docs/concepts/security/permissions#resource-table

It doesn't contain wildcard options (which are explained above on the page) but I think it helps with understanding what actions are available where.
