### ISSUE TITLE
Connection limit reached with limit -1

### ISSUE THREAD

**Issue by giulio1979** [hashicorp/boundary#1817]
Hi, after leaving my boundary client open over night I noticed session got closed with the message:

$ boundary connect -target-id ttcp_I7s0GSbk5T  -host-id hst_Nx0FSxEVJv  -listen-port 5432

Proxy listening information:
  Address:             127.0.0.1
  Connection Limit:    -1
  Expiration:          Thu, 06 Jan 2022 07:23:52 CET
  Port:                5432
  Protocol:            tcp
  Session ID:          s_dcBY3fIsLQ

Termination information:
  Reason:   No connections left in session

**To Reproduce**
1. Run `boundary authenticate  ...`
2. Run `boundary connect ...`
3. Leave unattended

**Expected behavior**
Connection remains active

**Additional context**
Boundary 0.7.3

**Comment by irenarindos** [comment]
I think the root cause here might be that the session reached its time limit and expired, though the termination reason given is incorrect. If you look at the proxy listening information, the expiration time is listed- is that when the session was closed?

To view your target’s time limit, use this command to see Session Max Seconds:
`boundary targets read -id <targetId>`

To update the time limit, use this command:
`boundary targets update tcp -id <targetId> -session-max-seconds <desired session limit>`

I’ve reproduced this with a time limit set to 2 seconds and also received the termination reason `No connections left in session` when it **should** read `Session has expired`. Thanks for finding this!

**Comment by irenarindos** [comment]
Re-opening to fix incorrect message on session expiration
