### ISSUE TITLE
AWS KMS doesn't work with instance role

### ISSUE THREAD

**Issue by ichasco-heytrade** [hashicorp/boundary#1818]
Hi,

I have configured boundary with this configuration:

```
kms "awskms" {
  purpose    = "root"
  region     = "eu-west-1"
  kms_key_id = "13f71062-f9da-4397-8dca-XXXXXXXX"
}
```

And it gives the next error:
```
boundary         | Error parsing KMS configuration: error fetching AWS KMS wrapping key information: NoCredentialProviders: no valid providers in chain. Deprecated.
boundary         | 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

The instance role has the correct policies:
```
kms:Encrypt
kms:Decrypt
kms:DescribeKey
```

Thanks in advance

**Comment by the-maldridge** [comment]
Hmm, I have almost the same configuration you do, but this works for me in us-west-2.  I'm going to discount the possibility that AWS regions are different here, because that seems unlikely.  I'm using the same KMS policy as well (https://github.com/resinstack/terraform-aws-boundary/blob/master/kms.tf) and things appear to be working.  Can you share what version you're running?

**Comment by ichasco-heytrade** [comment]
Hi,

I have the `0.7.3` version

**Comment by jefferai** [comment]
The AWS provider uses the official AWS Go library. This should pick up credentials from instance metadata, config files, web identity token files, or keys you've added directly to the configuration file.

I believe a recent change means that it does not currently support using environment variables. If that's what you're using, it may be the culprit.

@PPacent @sswati0 Regardless of whether that's the issue here we should probably enable environment variables at least as an option (this would be a change in go-kms-wrapping, then pulling that into Boundary), and probably by default, as our docs for KMS say that it's supported. I think this was changed with the work done to awsutil prior to the AWS dynamic host catalogs. I'd consider this high priority (it's not a lengthy fix).

**Comment by A-440Hz** [comment]
Hi, 

I believe I was able to replicate your error. I think the issue is the AWS environment provider expects all three AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN keys to be declared as environment variables in order to return a valid response. 

For instance, if you have only declared the access key and secret key as environmental variables, it will return those values together with an invalid session token. Alternatively, you can declare these values in your [config.hcl file](https://www.boundaryproject.io/docs/configuration/kms/awskms)

**Comment by the-maldridge** [comment]
This feels like not-a-bug.  The AWS docs are pretty clear in that if you intend to use the instance profile you must not export any environment variables.
