### ISSUE TITLE
Feature: zerotrust with credentials

### ISSUE THREAD

**Issue by chifu1234** [hashicorp/boundary#2119]
**Is your feature request related to a problem? Please describe.**
Today the user has full access(read) to the cred store & thus knows all credentials. This mechanism sometimes leaks some vulnerable information to the end-user & it reduces the user experience as they have to enter the credentials to the session.
 
**Describe the solution you'd like**
Boundary acts as ssh or RDP proxy. The admin can set propriety to a credential that the end-user does not have read or write access to these credential. If a user tries to connect to a system with ssh/RDP, the boundary proxy (worker) performs the authentication and then proxies the session back to the end-user.

**Describe alternatives you've considered**
- Using OTP for credentials (bad user experience)
- Use AD Users and let them handle by the HashiCorp vault (with a TTL) (bad user experience)

**Comment by karras** [comment]
@xingluw Is my understanding correct that a first iteration of this feature request was implemented in `0.10.0` with "Credential Injection"? Any plans to include this in the OSS version as this seems to be solely available in HCP Boundary at the moment or am I mistaken? :)

Thanks!

**Comment by xingluw** [comment]
Hi @karras, that is correct, it will only be available in HCP Boundary and there are no plans to implement this in OSS at this time.

**Comment by sandstrom** [comment]
I get that you want to make money to pay back all investors. 

But pushing for HCP (hosted cloud) of an auth-tool doesn't make sense to me. 

When you get hacked (will happen) or are down (will also happen) we'll suffer. 

Is there a paid offering where the injection feature is available?

We're a ~10 people company and pay for several "pro" versions of open-source products.

For "boundary pro" a fee per user and month would make sense for us. 

It should still be OS and we'd manage/host it, but there would be a license requirement and telemetry could report number of users back to HashiCorp for billing.

Any plans for such a thing?

**Comment by PPacent** [comment]
@sandstrom first off thank you for the interest in Boundary and for giving feedback to drive the product's direction. Your request for a pro-tier, self-managed version of Boundary's OSS offering is heard and we will keep this post open to gauge interest from the community. 

For now, for professional use cases the team is focused on building a compelling managed service of Boundary because we think the streamlined operations a managed service provides to users is the best way to make the tool broadly consumable. For practitioner use-cases, we remain committed to offering both Boundary OSS and HCP Boundary and letting users choose the delivery model that works best for them. Investing time and focus in a complex offering like HCP Boundary does unfortunately require saying no to other initiatives in the short-term, and we understand that a managed service will not be right for all customers. In the meantime, we plan to support customers with hesitancy to consume managed offerings in a couple of ways.

**Investing in HCP Boundary security and availability**
One of our top priorities for HCP Boundary is ensuring the managed surface is consumable even in secure environments. Self-managed workers already help limit access to customer environments and we are working on new features that will improve the security posture of accessing a highly secure private network. In addition, we will continue to improve the managed service with functions such as backup workflows, disaster recovery, and platform outage fallbacks. We will have some announcements in this vein at next week's [HashiConf Global conference](https://hashiconf.com/global/). 

**Continuing to build a compelling Boundary OSS offering**
We remain as committed to building a compelling and secure open source offering of Boundary. The use of single-use credentials instead of static, long-lived credentials, is one of the ways Boundary can help improve an organization’s security posture. Even without credential injection, the use of credential brokering with single-use credentials is a significant improvement in security posture vs other forms of credential management because the attack vector is so limited. We are continuing to improve the user experience for credential brokering to expand to a variety of dynamic credentials and these will be coming to open source Boundary as well as HCP Boundary.

**Comment by simonfelding** [comment]
You should really reconsider your stance on this issue. I'm sure there's lots of money to be made on support contracts like what oracle does. 

I work in a large IT company (7000 employees or so) that currently has a somewhat unpleasant UX for the auth process. Boundary with credential injection would be really great, but there's just no chance of convincing anyone to do a transition to a cloud based service - it's on-prem or nothing.

**Comment by JannikZed** [comment]
For us, it was also a big shocking now, that we invested a few days setting up Boundary OSS (as our customer is not allowing hosted services from US corps..), after evaluating everything with HCP and to realise now, that all needed features don't work and we would need to switch from SSH certs back to SSH password in order for boundary to be able to broker it .. really bad experience.

**Comment by jory3** [comment]
Same here: Only after setting up a test environment I found out, that "credential injection", something I considered as the core feature of boundary, doesn't work on premise. Currently, the OSS version of boundary is not much more than a password manager with team capabilities, combined with an SSH client - but much more complicated to setup, use and maintain.

**Comment by PPacent** [comment]
Hi all -  @chifu1234, to your original request on this thread, Boundary now supports credential injection in HCP Boundary as well as Boundary Enterprise (customer-hosted version of Boundary). With credential injection, the user never sees the credential required to authenticate to the target. This provides a passwordless experience for the user, as the worker does both session establishment and authentication to the target on behalf of the user. We currently support credential injection for SSH credentials and plan to expand to other types of protocols in the future. You can learn more about credential injection [here](https://developer.hashicorp.com/boundary/docs/concepts/credential-management#credential-injection-hcp-ent).

@jory3, @JannikZed, @simonfelding, @sandstrom - there is now self-managed edition of Boundary that supports credential injection. Boundary Enterprise is now available which includes all premium features of Boundary - including credential injection, [multi-hop sessions](https://www.hashicorp.com/blog/boundary-0-12-introduces-multi-hop-sessions-and-ssh-certificate-injection), and session recording. You can learn more [here](https://www.hashicorp.com/blog/boundary-0-13-introduces-ssh-session-recording-boundary-enterprise-and-more?ajs_aid=617143ca-c122-4daf-a7b1-5aa551a27a8a&product_intent=boundary).

**Comment by simonfelding** [comment]
That's nice, thank you for listening!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
