### ISSUE TITLE
Dynamic host set: EC2 DescribeInstances API calls timeout

### ISSUE THREAD

**Issue by psypuff** [hashicorp/boundary#2224]
**Describe the bug**
Using dynamic host sets (AWS specifically, haven't tried the Azure one yet) in a large environment results in the following error:
```
{"id":"<REDACTED>","source":"https://hashicorp.com/boundary/4466e4d3c372/controller","specversion":"1.0","type":"error","data":{"error":"rpc error: code = Unknown desc = error running DescribeInstances for host set id \"<REDACTED>\": SerializationError: failed decoding EC2 Query response\n\tstatus code: 200, request id: 55f65e01-476e-4b4d-93b0-9e38b419b445\ncaused by: context deadline exceeded (Client.Timeout or context cancellation while reading body)","error_fields":{},"id":"<REDACTED>","version":"v0.1","op":"plugin.(SetSyncJob).syncSets","info":{"catalog id":"<REDACTED>","msg":"listing hosts"}},"datacontentype":"application/cloudevents","time":"2022-06-21T08:40:33.258736566Z"}
```

We tried splitting it into multiple host sets with different filters, still some queries timed out.
The biggest dynamic host sets we managed to produce were around 300 hosts. Some queries should've returned less hosts but timed out as well so host count might not be the only factor here.

**To Reproduce**
1. Create a dynamic host catalog and a host set with the `instance-state-name=running` filter to fetch all running EC2 instances within an environment containing 1000s of instances
2. Tail the controller log
3. See error mentioned above

**Expected behavior**
All running EC2 instances should be populated under the host set / catalog.

**Additional context**
Boundary version: 0.9
Setup: Docker on EC2 VMs

Looking at the AWS plugin code it seems the `DescribeInstances` call uses the default HTTP client with the default timeout config. We're suggesting exposing some config to control the timeout of such calls.

We opened a similar [issue](https://github.com/hashicorp/boundary-plugin-host-aws/issues/15) for the AWS plugin repo as it might require changes in both repos.

**Comment by sswati0** [comment]
Thanks for reporting the issue. We are looking into it.

**Comment by jefferai** [comment]
Hi there -- I'm looking at two avenues for how this can happen. The first is when a set is written with its filter -- the plugin does a dry run to make sure the filter is able to be used. This is synchronous, which means there are two timeouts relevant here:

* The [`max_request_duration`](https://www.boundaryproject.io/docs/configuration/listener/tcp#max_request_duration). This is the maximum amount of time that the Boundary server allows a request to be handled and defaults to 90 seconds.
* The timeout for the actual client making the call. This is set by the Boundary CLI client _if_ you're using that and defaults to 60 seconds. This can be overridden with the `BOUNDARY_CLIENT_TIMEOUT` env var -- there is currently no flag for it.

This is important because if this doesn't successfully complete then saving the set won't happen properly so it's a necessary first step. (I could consider allowing the dry run to be skipped, but right now that's not possible.)

The other timeout would be when boundary's scheduler runs the job; still digging into that.

**Comment by jefferai** [comment]
I checked with the person that knows the scheduler best (@louisruch ) and when the job is being run async there is no timeout that is being imposed by Boundary (unless one is built into the AWS SDK, although I'm not aware of any). This plus the exact message you're seeing leads me to believe that you're seeing this when you are creating or updating a host set and are hitting the synchronous case. Can you confirm/deny? If so, can you see if changing those values helps you?

**Comment by psypuff** [comment]
Hi @jefferai,

Thanks for taking a look at it, this blocks the implementation of Boundary in our org (and I believe other orgs with large amount of VMs as well).

The creation of the host set succeeds (using either UI, CLI or TF). Once it has been created, the error shows up periodically in the controller log (every time a `DescribeInstances` call takes place I believe). Sorry for not being clear on that point.

Since there's indeed no timeout imposed by Boundary, and the [AWS SDK uses the default http client](https://github.com/aws/aws-sdk-go/blob/3d1156abcf6c6a02b9ef805d3d8abb4971a38f12/aws/config.go#L76-L78), it led me to believe it uses its default timeout settings (I think it's 60s or 90s).
I'm not familiar with golang but as deep as I was able to get it seems you could either override the default http client [as AWS suggests](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/doc.go#L45-L55) by passing a `Config` struct when [instantiating the EC2 client](https://github.com/hashicorp/boundary-plugin-host-aws/blob/main/plugin/state.go#L274) or pass the timeout setting through the `Context` which the [AWS SDK seems to support](https://aws.amazon.com/blogs/developer/context-pattern-added-to-the-aws-sdk-for-go/) by using the [DescribeInstancesWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeInstancesWithContext) func.

Thanks again and LMK if you need more info.

**Comment by jefferai** [comment]
Hi @psypuff ,

The default `Timeout` value on `http.Client` is unset, and a timeout of zero means no timeout; `http.DefaultClient` is an empty `Client` so shouldn't be setting the timeout. However, the client uses `DefaultTransport` which while not explicitly containing a request timeout _does_ have `IdleConnTimeout:       90 * time.Second`.

This makes me wonder if it's actually triggering _idle_ timeout while waiting for a response as opposed to a general request timeout.

In that case rather than make a configurable timeout I may just try updating the transport in use to have a very long idle timeout.

If I am able to make you some builds with updated code, would you be able to test them out? If so, what platform/arch?

Thanks!

**Comment by psypuff** [comment]
Thanks @jefferai, I'd definitely try these out.
Ubuntu 18.04 on x86 should be fine.

**Comment by jefferai** [comment]
@psypuff sorry, got really swamped. I can make a build -- would you be okay with a build off of our `main` branch containing this change? I assume since you're blocked so far that you're not in a production scenario.

**Comment by psypuff** [comment]
Definitely not a production scenario but since this effort has been paused for the past 2 months on our side, we've started eyeing other zero-trust solutions which I'm trying to push back on.
Generally, I have no problem with a build off of the `main` branch as long as you're confident it won't introduce much noise.

**Comment by jefferai** [comment]
Hi @psypuff,

I've put up a build at https://drive.google.com/file/d/1VpkBhnsf2MWNO_saCxQJ2t2tax7y_8aq/view?usp=sharing -- it's linux/amd64 which I assume is fine.

The change that should be pulled in here is [this here](https://github.com/hashicorp/boundary-plugin-host-aws/compare/main...jefferai-custom-http-client#diff-e88048690c87993a856e7fcdd401c68a85a22ac5bcca423c165bcc10cab59eb6R264). It's more ensuring that timeouts aren't set than ensuring that any given one is; I'm not sure this is the right long term solution in case there could be some hang, but it's for the moment something I have time to do rather than plumbing a lot of custom timeout attributes through (which I'm not even sure is actually better anyways :-)  )

There is one circle I haven't been able to square with respect to your experience. You didn't indicate that you saw errors when you were making the Boundary API calls to create the host set, but it does a synchronous DescribeInstances at that time. Based on `http.DefaultTransport`'s idle time out of 90 seconds, and the Boundary API client's default request timeout of 90 seconds, I'd expect that if the idle timeout were the issue that you'd see the same problem when creating or updating a host set, unless you've overridden those values...

**Comment by psypuff** [comment]
Thanks @jefferai,

I tried testing it yesterday and ran into [this](https://github.com/hashicorp/boundary/pull/2407) issue. Unless the fix would get merged soon and your branch could get rebased, it'd be great if you could rebase your branch over the 0.10.1 version. If not, I'd have to setup a new empty DB and re-init our config but that would take longer.

Please LMK what's possible on your side.
Thanks.

**Comment by psypuff** [comment]
@jefferai I see the DB migration fix was merged and released in 0.10.3. Could you please rebase your branch on top of this version?

Another point worth mentioning is that the error I referred to in the beginning of this issue shows up in the log on the 22nd second of every minute (I guess the `DescribeInstances` calls are scheduled every minute). Though it seems it doesn't really align with any default timeout we mentioned so far.

**Comment by jefferai** [comment]
Hi @psypuff ,

[Here's an update](https://drive.google.com/file/d/117Ltuc7sF_9oGIzehiVNyORaQC_t4S_5/view?usp=sharing).

As far as the minute timing, I do not offhand remember what the default cadence is -- a minute seems possible -- but it can be tuned via [sync_interval_seconds on a host set](https://www.boundaryproject.io/api-docs/host-set-service). It's also possible that it's not one minute but that's the retry logic if the job fails.

**Comment by psypuff** [comment]
Thanks for the prompt reply @jefferai.

I'm happy to say your build solves the timeout issue and all hosts are now listed in the host-set. 🎉 
There's another issue now - the browser seems to be incapable of rendering that many hosts on Boundary's UI (a few thousands), it spits the following error: `net::ERR_INSUFFICIENT_RESOURCES`. This isn't that important for us since the CLI works well and we could work around it by splitting the hosts into multiple host-sets.

Thanks for your help and attention 🙏

**Comment by jefferai** [comment]
Awesome! Glad to hear!
