### ISSUE TITLE
systemd unit name doesn't allow instances ('@controller' or '@worker')

### ISSUE THREAD

**Issue by ataraxia937** [hashicorp/boundary#2358]
**Describe the bug**
The boundary.service file uses the %i variable, so it's clearly meant to be run as 'systemd@controller.service', 'systemd@worker.service', and so on.

But systemctl/systemd doesn't understand how to create instances on a unit whose name doesn't end in an '@' sign. So in order to actually use the unit file, I have to copy /usr/lib/systemd/system/boundary.service to /etc/systemd/system/boundary@.service.

Then I am able to `systemctl enable boundary@controller` successfully.

Please rename the unit file to `boundary@.service`.

**To Reproduce**
1. See error on running `enable` command:
`# systemctl enable boundary@controller`
Failed to enable unit: Unit file boundary@controller.service does not exist.

**Expected behavior**
systemctl should be able to create the instance links.

**Additional context**
I'm running on Amazon Linux 2.

**Comment by rjhornsby** [comment]
I haven't looked at the debian side, but I think this is a bug in how the RPM is constructed for the rpm-based systems, which includes AmazonLinux.

The unit file should probably be `boundary@controller.service`. This will cause systemd to replace occurrences of `%i` with `controller` when parsing the unit file contents.

As noted above, the RPM writes out a `boundary.service` unit file. Systemd doesn't handle this properly because it has no value (there's no `@controller` or `@worker` in the filename) to assign to `%i`. The unit file uses this to dynamically refer to the boundary configuration file

`ExecStart=/usr/bin/boundary server -config=/etc/boundary.d/%i.hcl`

The RPM creates `/etc/boundary.d/controller.hcl` (and `worker.hcl`) so it appears the RPM author's intent was to have `boundary@controller.service` and/or `boundary@worker.service` unit files.
