### ISSUE TITLE
Desktop app not working with v0.11

### ISSUE THREAD

**Issue by Akisaji** [hashicorp/boundary#2697]
Recently we upgraded from v0.7.4 to v0.11.0 and with the upgrade no version of the desktop app works anymore for our devs.

From desktop app version 1.4.4 or greater, the desktop app can no longer connect to the boundary server and gives the following popup: 
![image](https://user-images.githubusercontent.com/43436777/206711503-7e54bc4d-eebf-4fa4-bb99-5a0b27b63d5b.png)

The URL used is the same URL as before the upgrade, and when reverting boundary version this URL works again.

While other version before 1.4.4 of the desktop app are able to connect to the boundary server but when trying to connect to a target the following error is shown:
![image](https://user-images.githubusercontent.com/43436777/206712140-d7ae83a0-5c29-4e9e-9507-0275009267e0.png)

Is this a fault in the boundary desktop app, or do we need to change something on the boundary setup?

Connecting through the CLI works just fine with the upgrades version of boundary.

If more info on the setup is required let me know

**Comment by randallmorey** [comment]
Hi there and thanks for your interest in Boundary.  In order to better assist you, we'd like to learn more about your use case.  To ensure the privacy of your sensitive information, we'd be happy to follow up via boundary-issue-investigations@hashicorp.com.  Please email us at this address with the following information:

Subject:  Desktop app not working with v0.11 #2697

- Boundary controller (server) version
- URL of your Boundary controller, which you were unable to connect to from Boundary Desktop v1.4.4

Thank you!

**Comment by Akisaji** [comment]
@randallmorey I tried to mail to [boundary-issue-investigations@hashicorp.com](mailto:boundary-issue-investigations@hashicorp.com) with the additional info but i'm getting a failure mail that it can't be delivered. Is this the correct email?

**Comment by randallmorey** [comment]
@Akisaji I mistyped the email.  Try this:  boundary-issues-investigations@hashicorp.com

**Comment by Akisaji** [comment]
@randallmorey Still nothing..

```
Your message wasn't delivered to boundary-issues-investigations@hashicorp.com because the address couldn't be found, or is unable to receive mail. 
```

**Comment by PPacent** [comment]
Apologies @Akisaji the issue you experienced should be solved now. Please try to resend.

**Comment by PPacent** [comment]
This issue appears to have been caused by `u_anon`, the `user` resource for unauthenticated Boundary users, having insufficient privileges. Anonymous user u_anon must be a member of a role with a grant to list auth methods and scopes to use Boundary Desktop. 

Boundary autocreates a `global_anon_listing` role for `u_anon` in dev mode and HCP Boundary.
The role has the following grants:
<img width="769" alt="Screen Shot 2023-02-13 at 11 45 34 AM" src="https://user-images.githubusercontent.com/23266747/218560626-d38311af-8157-4183-bf24-bd5935842939.png">

Adding these grants to a role in `global` scope and ensuring `u_anon` is a member should resolve the issue.
`id={{account.id}};actions=read,change-password
`id=*;type=scope;actions=list,no-op
`id=*;type=auth-method;actions=list,authenticate`
