### ISSUE TITLE
debug level logging

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/boundary#3145]
**Describe the bug**
Debug level logging seems to be missing/ignored.

**To Reproduce**
1. Run a boundary command with the logging level increased, ie `BOUNDARY_LOG_LEVEL=debug boundary database init...`
2. Info/warning/error logs, but no debug logs

**Expected behavior**
Expected to get more verbose/detailed logging output

**Additional context**

While trying to troubleshoot boundary database init "could not connect to database postgresql://...", was not able to increase log level beyond `INFO` to get any more detail on the problem other than "could not connect".. Best guess from trial and error is that for some reason (url encoding?) boundary does not like special characters in the password. All attempts to increase the log verbosity were ignored.

The docs discuss the event sinks, but don't mention log levels. From familiarity with Terraform and Vault, `BOUNDARY_LOG_LEVEL` env var is a reasonable guess, and in fact is referenced in various places in the boundary code, but seems to have no effect on output.

**Comment by jimlambrt** [comment]
Good morning!   

Boundary doesn't really have log levels.  We do support a few different event types and audit events support allow/deny filters to limit the data sent to a sink from the "fire hose" of audit events boundary can/does emit.

With that said, in the case of `boundary init database` and this specific error, I'm not sure it matters.   Boundary uses a std [Postgres URL](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) to specify its connection info.   

If you're looking to validate the connection URL independent of boundary, I'd just using [pg_isready](https://www.postgresql.org/docs/current/app-pg-isready.html) via something like: `pg_isready -d "postgresql://...`

**Comment by rjhornsby** [comment]
@jimlambrt thanks. I was able to connect to the db without an issue feeding the exact same url to `pgsql` that boundary was failing with - which is why I think probably it's getting munged / URL encoded somewhere along the way. Limiting password characters to `[A-z0-9]` resolved Boundary. Either way, it wasn't meant to raise it as a separate issue but as a specific example of trying to troubleshoot that led me to the logging output.

> Boundary doesn't really have log levels. We do support a few different event types and audit events support allow/deny filters to limit the data sent to a sink from the "fire hose" of audit events boundary can/does emit.

I saw this in the docs and while different event types is fine and being able to filter them is also fine, it's a bit odd that there's no way to adjust the log verbosity? The logs themselves prefix most `hcl_log` text type messages with `[INFO]` - indicating there is a log level somewhere involved. I understand the different types of events - but events are a subset of logs. While an event says "this thing happened," usually in reference to the external world, a log includes diagnostic information about what the underlying code is doing.

The approach here to "[not] really have log levels" is a significant departure from other HCP tools including vault, terraform, and consul as well as from more or less universally accepted logging conventions. Without being able to adjust the level of logging detail, the choice comes down to either not enough logs to figure out what's happening when something goes wrong, or a production environment with large amounts of noise - and the added load that comes with that - in the logs.

"Something goes wrong" could mean I've configured something wrong or there's a bug in the code. I'm sure I'm not the only one who uses increased log verbosity in consul, terraform, and vault for understanding what I'm doing when learning/setting up the tool as well as when doing things like writing a TF provider or digging into why <thing> in vault isn't doing what's expected. Whatever the case, higher log levels are a critical tool for troubleshooting, fixing, and reporting issues upstream. We lower the level when we don't need the detailed picture, but want to be able to see a broader view without having compete for brain capacity with irrelevant content.

**Comment by jimlambrt** [comment]
Postgres URLS are...  a URL, so if you use special characters they will need to be escaped like any other URL.

Boundary provides a `hcl_log` format, so if our users have existing tools to parse that format they will still work with boundary events.  

Boundary events are not a subset of any logs; they are a superset of all logs.  We chose to event whatever is need and then provided the ability to easily filter (allow/deny) whatever users need/prefer into sinks.  For example, boundary audit events include worker status events which would allow you to "debug" many worker issues.  These worker status events occur about once a sec, so if ya don't need them, then it's trivial to filter that very specific "noise" out of the event sink.  Or on the other hand, if that's all you need: you can filter only those worker status event into your sink.  Or you could chose to easily filter only status events from a very specific worker, since it's trivial to do so.  In many ways this is much more powerful than traditional log levels which have no way to specify allow/deny filtering.

Yes it's different than other HashiCorp products and that was intentional.  We're trying to provide a more powerful way to find exactly what you need and quickly understand and fix a problem. 

Oh... boundary also chose events (using the "std" cloudevents schema) so users could easily forward them to external systems.  With that said, boundary events aren't exclusively internal or external events.  We chose to let the users decide how best to empower their experiences.  If you want to fwd (event) a specific set of system and/or error events to a SEIM or Splunk, then boundary makes it pretty trivial for users to extend boundary in that manner.  Checkout cloudevents.io for more info, but there are already adapters from vendors to forward/ingest cloudevents.

**Comment by rjhornsby** [comment]
> Postgres URLS are... a URL, so if you use special characters they will need to be escaped like any other URL.

durh. you're right. I had it backwards in my brain for some reason.

> Checkout cloudevents.io for more info

I saw that - it's a very interesting idea to wrap a common, standardized structure around log/event messages. I guess it's not unlike NCSA formats like CLF for http servers, only even more general purpose, and with JSON. It certainly makes writing log/event parsers easier given that nearly all the work is already done.

Thanks for the explanation.
