### ISSUE TITLE
Authentication tokens are not stored to keychain on Mac when using `-format=json`

### ISSUE THREAD

**Issue by mmussomele** [hashicorp/boundary#3159]
**Describe the bug**
Authentication tokens are not stored to keychain on Mac when using `-format=json`

**To Reproduce**
1. Run `boundary authenticate oidc --format=json` on MacOS
2. Run any command that would require the resulting token
3. The command should fail

**Expected behavior**
Command 2 should succeed.

**Additional context**
Maybe this behavior is intended (e.g. "the user asked for the json output so they intend to save the token themselves"), but none of the docs I could find ([here](https://developer.hashicorp.com/boundary/docs/api-clients/cli#output-options), [here](https://developer.hashicorp.com/boundary/docs/oss/installing/run-and-login), [here](https://developer.hashicorp.com/boundary/tutorials/access-management/oidc-auth) or by doing `boundary authenticate oidc --help`) indicate that this behavior will occur. The token is just silently omitted from the keychain.

**Comment by hugoamvieira** [comment]
Hey @mmussomele,

I've looked into this and can confirm it is intended behaviour. 

Since outputting in JSON is designed to allow for sending the output to other tools, it's reasonable to assume in this case that the user wants that authentication information to be passed along to another tool for storage.

You can find that [in this function](https://github.com/hashicorp/boundary/blob/main/internal/cmd/commands/authenticate/funcs.go#L39-L43), we don't attempt to store to the keychain if we are outputting in JSON.

As you mentioned, I haven't found any documentation on this, so I have a PR up to fix that (see above)

Thanks for your report! 😃
