### ISSUE TITLE
Ability to toggle dark mode

### ISSUE THREAD

**Issue by Vivalldi** [hashicorp/boundary#719]
**Is your feature request related to a problem? Please describe.**
Dark mode is currently enabled solely on the `prefers-color-scheme` CSS media query. Users are unable to indicate if they want to view in a mode different than their system

**Describe the solution you'd like**
Add a toggle button to the current user profile "rose menu" (top right)

**Describe alternatives you've considered**

- Toggle in the header next to user profile
- Toggle in a user profile page (not sure there is one yet)

**Explain any additional use-cases**
None at this time

**Additional context**
None at this time

**Comment by jack1902** [comment]
Going to link two issues since i see a consistent method use in the UI dark mode between two hashicorp projects. Within `Waypoint` the same method of `dark mode` is used.

Relates to: https://github.com/hashicorp/waypoint/issues/541

I mentioned that it would be a cool idea to have the same ability as `slack` to provide options on using OS setting vs a user setting

<img width="569" alt="Screenshot 2020-10-16 at 21 03 13" src="https://user-images.githubusercontent.com/39212456/96305493-dc28d600-0ff5-11eb-8230-8323323f21c0.png">

**Comment by malnick** [comment]
Thank you for raising this! We're working on a toggle in our UI and will have an update on this in a couple of weeks, stay tuned!
