### ISSUE TITLE
(question): SOCKS5 proxy & DNS over HTTPS as L7 VPN alternative ?

### ISSUE THREAD

**Issue by lukasmrtvy** [hashicorp/boundary#753]
Is possible that Boundary will someday will work as VPN alternative? Yes, its possible to do L4 now, thats super good, but I am talking now about L7 HTTP. 

Zerotrust/Beyondcorp is really expensive these days and for certain environments its still a taboo.

There are not so many cloud-native VPN solutions ( AFAIK only OpenVPN Cloud, AS, Tailscale and some Enterprise FWs can handle SAML/OpenID integrations,ACL and audits, but these are still some reworked legacy apps, Tailscale is not, but its quite expensive. )

Related: https://github.com/inlets/inlets

SOCKS5 server:
https://github.com/shadowsocks/go-shadowsocks2
DNS with rfc8484 support:
https://github.com/coredns/coredns

**Comment by malnick** [comment]
Thanks for the question @lukasmrtvy - You can proxy HTTP traffic today with Boundary, since it rides on top of TCP. We have a useful `connect` sub command to fork `curl` for exactly this purpose: `boundary connect http...`. You can also run `boundary connect` and point your browser at `localhost:<ephemeral_port>` of the proxied target. 

This means you can effectively use Boundary in place of something like OpenVPN for accessing something like a web server on a private network. Let me know if this is what you were looking for or if you had other requirements around proxying an HTTP session. Thanks!

**Comment by pbernal** [comment]
@lukasmrtvy  - we're closing this out as @malnick has provided a response. Let us know if you need additional information. Thanks for the question!

**Comment by lukasmrtvy** [comment]
@malnick thanks !
Idea was to control os proxy settings via boundary cli and at the same time serve SOCKS5 and DNS over HTTPS ( https://github.com/shadowsocks/go-shadowsocks2 ) or DNS itself ( https://github.com/coredns/coredns ).

This should work as L7 HTTP, something like `boundary vpn-proxy ...` command. ( this will allow users access services in browser normally e.g. https://gitlab.example.com, https://grafana.example.com ) After session, proxy settings should be restored.
