### ISSUE TITLE
Boundary for VFX HPC workflows: Will it work without users having emails in an FQDN? Is a VPN still possible?

### ISSUE THREAD

**Issue by queglay** [hashicorp/boundary#764]
I'm excited to see improving session authentication methods like what Boundary might offer.  I am surprised in this era how difficult it still is to provide simple secure access to a private network for other open source projects.  The only other close contender to a product like this that I've seen is Teleport, but I don't think its able to solve my use case for open source IAC with users that don't have emails in an FQDN.

**Is your feature request related to a problem? Please describe.**
A problem I have encountered in my own open source IAC project for VFX workflows is I want to provide any random group of artists the ability to collaborate on a project, and dissolve their infra when they are done.  This has been a very difficult problem to map.

That might mean they don't even have a FQDN, and this is a pain point for me, because most authentication with MFA these days, or even ssh certificates carry the presumption of a FQDN.

I'd like to see in a product like Boundary, the ability to provide access and admin of private subnets without worrying about an FQDN, and still ensure MFA is used.  There might be 20 different artists with different emails (probably standard gmail accounts), and I'd like them all to be able to collaborate with ease, and hopefully boundary could allow something like that.

**Describe the solution you'd like**
Boundary could be able to send an invite to any email address (including those not under a company FQDN), authenticate with MFA, and optionally enable VPN like solutions as well.  In VFX, artists may have their own compute capability, but may share a cluster of cloud based spot instances, and usually seamless communication for those resources really only works with a VPN since nodes and schedulers (like AWS deadline) need to identify each other for a broad set of processes to function for rendering images.  If a VPN isn't possible, then boundary would still be great for initial configuration of a VPN via Vault and using an SSH CA.

**Describe alternatives you've considered**
Teleport (but it doesn't have OIDC for OSS), everything the old school way with shell scripts, Vault.

**Explain any additional use-cases**
Any community based open source IAC project that needs to invite collaborators into a private network to produce content/output.

Backstory: If anyone else is interested in my SIGGRAPH presentation on conceptually what I'd like to apply boundary to in my own project you can checkout my presentation here https://www.youtube.com/watch?v=Ahw8pXu5RyY
At this point, it's a proof of concept for a single user, but the next phase of the project is to enable collaborators.

**Comment by PPacent** [comment]
Hi @queglay, thanks for your interest in Boundary! It sounds like there's a few different feature requests here, but the primary one that sticks out is support for Boundary users across potentially different identity providers. This is a major goal in [our future roadmap](https://www.boundaryproject.io/docs/roadmap) and will be first enabled with OIDC authentication support. This will allow Boundary administrators to onboard OIDC providers as auth methods to Boundary for their users. With OIDC, MFA could also be enabled through the OIDC provider(s) being used. 

If there's other feature requests as part of this ticket that you would like us to track, please feel free to do so by creating another ticket. Otherwise, we will close this ticket as OIDC authentication support is actively being worked on.
