### ISSUE TITLE
JSON output invalid due to errors on stdout

### ISSUE THREAD

**Issue by jorhett** [hashicorp/boundary#791]
**Describe the bug**

JSON output is invalid due to errors on stdout.

**To Reproduce**

1. Without being authenticated, run `boundary auth-methods list -format=json 2> /dev/null`
2. First line of output is not valid JSON

```
No saved credential found, continuing without
[{"id":"ampw_foobar","scope_id":"global","scope":{"id": ...
```

**Expected behavior**

Valid JSON that could be used by a program, like `jq` to get the auth method id:
```
    boundary auth-methods list -format=json |  jq -r '.[] | select(.type=="password").id'
```

**Additional context**

This is the required workaround, which is messy:
```
    boundary auth-methods list -format=json |grep -v 'No saved credential' | jq '.[]'
```

**Comment by jefferai** [comment]
This is kind of a tricky one.

We assume that you will want to load a saved token since this would be normal behavior, and that if you don't want to, that you would disable it via `-keyring-type none`. So arguably this is an error and we should switch it to stderr.

On the other hand, if you _aren't_ expecting a saved token to be available, but have not actually disabled it, then this is useful information but not actually an error, and it's easy to work around by simply telling the CLI not to try to look for a saved token.

So this is really about user expectation. That said, I'm in favor of switching this to stderr, because it will help with output redirection cases and it can still be disabled via setting the keyring type.

**Comment by jorhett** [comment]
> and it's easy to work around by simply telling the CLI not to try to look for a saved token

Just FYI we're putting this in people's shell profiles to simplify logging in... which is before they know what boundary is, nevermind have made a choice about keyring ;-)

```
export BOUNDARY_AUTH_METHOD_ID=$(boundary auth-methods list -scope-id=global -format=json | jq -r '.[].id')
```
