### ISSUE TITLE
location-aware proxy assignment

### ISSUE THREAD

**Issue by lkd** [hashicorp/boundary#880]
**Is your feature request related to a problem? Please describe.**
One impedence mismatch I'm having is to have just one Boundary controller, storing state in one Postgres installation, controlling a distributed group of workers in various Amazon Web Services regions, without punching security group openings across regions.

I'd prefer not to implement region-locality by installing multiple copies of Boundary controller with multiple backing instances to prevent, say, a us-west-1 worker from attempting to connect to an ap-northeast-1 host/target.

**Describe the solution you'd like**
- hosts or host sets could have a notion of their tags.
- workers could have a notion of "only service hosts or host sets with the following tags"
- the controller considers these tags and attempts to match up session authorizations for specific hosts with workers that match the tag constraints

**Describe alternatives you've considered**
As above, one not-great alternative I'm considering is deploying one boundary controller+workers restricted to a given region. One issue is that I have to organize my day job's IaC to repeatedly copy user principals around since OIDC isn't here yet.

**Explain any additional use-cases**
Having tags to separate hosts and relate them to specific workers under operator control could help reduce the complexity of Boundary installations for reasons other than locality or security rules. (But <- are my concerns for now).

**Comment by PPacent** [comment]
Thanks for the interest and contributing the suggestion, @lkd! We agree, it would be great if administrators were able to constrain connections to some targets through particular workers. As you noted, this would be helpful for latency (ensuring relative locality between targets and workers that connect to them) and also for data security concerns (selectively peering workers with a private network/vpc on which a target may reside instead of peering ALL workers).

Your post is very timely as we are actively working on this feature :) - stay tuned for this in a release due in the coming weeks.

**Comment by springroll12** [comment]
Was this fixed as of 0.1.5 with this [PR](https://github.com/hashicorp/boundary/pull/862)?
