### ISSUE TITLE
Format json error on authenticate password

### ISSUE THREAD

**Issue by Akisaji** [hashicorp/boundary#992]
**Describe the bug**
Error when authenticating with boundary with -format json

**To Reproduce**
1. Run `boundary dev`
2. Run `boundary authenticate password -auth-method-id ampw_1234567890 -login-name admin -format json -password password`
3. See error

**Expected behavior**
To get a json response

**Additional context**
The format table works fine

This error only occurs on this boundary version
```
Version information:
  Git Revision:        c0f33f982c87c0eb4127cb16cf06b03a37b91dbd
  Version Number:      0.1.8

```

Go version
```
go version go1.16.1 linux/amd64
```

Actual error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1244e7d]

goroutine 1 [running]:
github.com/hashicorp/boundary/api.(*Response).HttpResponse(...)
	/go/api/response.go:22
github.com/hashicorp/boundary/internal/cmd/base.(*Command).PrintJsonItem(0xc00013a000, 0x1b3bce0, 0xc000496050, 0x156ce20, 0xc000826000, 0xc000504570)
	/go/internal/cmd/base/format.go:237 +0x3d
github.com/hashicorp/boundary/internal/cmd/commands/authenticate.(*PasswordCommand).Run(0xc000504000, 0xc000138030, 0x8, 0x8, 0xc0002ec020)
	/go/internal/cmd/commands/authenticate/password.go:159 +0xeb2
github.com/mitchellh/cli.(*CLI).Run(0xc0002c6f00, 0xc0002c6f00, 0xc0002ed340, 0xc00000df80)
	/root/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x1cf
github.com/hashicorp/boundary/internal/cmd.RunCustom(0xc000138010, 0xa, 0xa, 0xc00039fe60, 0xc000114058)
	/go/internal/cmd/main.go:186 +0x846
github.com/hashicorp/boundary/internal/cmd.Run(...)
	/go/internal/cmd/main.go:92
main.main()
	/go/cmd/boundary/main.go:13 +0xda

```

**Comment by matthiasantierens** [comment]
Same here

**Comment by jefferai** [comment]
Apologies for that. We made some large changes in the CLI to auto generate and update how the JSON output gets formatted (as discussed in the release notes) and while the majority of the CLI is now generated, this command isn't. It was tested along the way but it seems some later change broke it. I checked and our CLI-level tests didn't catch this because although in _most_ cases those tests use JSON formatted output, in this case they rely on the token helper to pass the token between tests. We'll make sure it gets fixed for the next release and a test added.
